config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("reservations/", include("reservations.urls", namespace="reservations")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("lists/", include("lists.urls", namespace="lists")),
    path("conversations/", include("conversations.urls", namespace="conversations")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as room_views

app_name = "core"

urlpatterns = [path("", room_views.HomeView.as_view(), name="home")]

lists/urls.py
from django.urls import path
from . import views

app_name = "lists"

urlpatterns = [
    path("toggle/<int:room_pk>", views.toggle_room, name="toggle-room"),
    path("favs/", views.SeeFavsView.as_view(), name="see-favs"),
]

reservations/urls.py
from django.urls import path
from . import views

app_name = "reservations"

urlpatterns = [
    path(
        "create/<int:room>/<int:year>-<int:month>-<int:day>",
        views.create,
        name="create",
    ),
    path("<int:pk>", views.ReservationDetailView.as_view(), name="detail"),
    path("<int:pk>/<str:verb>", views.edit_reservation, name="edit"),
    path("mine", views.MyReservationView.as_view(), name="see-mine"),
]

users/urls.py
from django.urls import path
from . import views
from rooms import views as room_views

app_name = "users"

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("login/github/", views.github_login, name="github-login"),
    path("login/github/callback/", views.github_callback, name="github-callback"),
    path("login/kakao/", views.kakao_login, name="kakao-login"),
    path("login/kakao/callback/", views.kakao_callback, name="kakao-callback"),
    path("logout/", views.log_out, name="logout"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path(
        "verify/<str:key>/", views.complete_verification, name="complete-verification"
    ),
    path("update-profile/", views.UpdateProfileView.as_view(), name="update"),
    path("update-password/", views.UpdatePasswordView.as_view(), name="password"),
    path("<int:pk>/", views.UserPofileView.as_view(), name="profile"),
    path("switch-hosting/", views.switch_hosting, name="switch-hosting"),
    path("switch-language/", views.switch_language, name="switch-language"),
]

users/forms.py
from django import forms
from . import models


class LoginForm(forms.Form):

    email = forms.EmailField(widget=forms.EmailInput(attrs={"placeholder": "Email"}))
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={"placeholder": "Password"})
    )

    def clean(self):
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")
        try:
            user = models.User.objects.get(email=email)
            if user.check_password(password):
                return self.cleaned_data
            else:
                self.add_error("password", forms.ValidationError("Password is wrong"))
        except models.User.DoesNotExist:
            self.add_error("email", forms.ValidationError("User does not exist"))


"""
class SignUpForm(UserCreationForm):

    username = forms.EmailField(label="Email")
"""


class SignUpForm(forms.Form):

    first_name = forms.CharField(
        max_length=80, widget=forms.TextInput(attrs={"placeholder": "First Name"})
    )
    last_name = forms.CharField(
        max_length=80, widget=forms.TextInput(attrs={"placeholder": "Last Name"})
    )
    email = forms.EmailField(widget=forms.EmailInput(attrs={"placeholder": "Email"}))
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={"placeholder": "Password"})
    )
    password1 = forms.CharField(
        widget=forms.PasswordInput(attrs={"placeholder": "Confirm Password"}),
        label="Confirm Password",
    )

    def clean_email(self):
        email = self.cleaned_data.get("email")
        try:
            models.User.objects.get(email=email)
            raise forms.ValidationError("User already exist with this eamil")
        except models.User.DoesNotExist:
            return email

    def clean_password1(self):
        password = self.cleaned_data.get("password")
        password1 = self.cleaned_data.get("password1")

        if password != password1:
            raise forms.ValidationError("Password confirmation does not match")
        else:
            return password

    def save(self):
        first_name = self.cleaned_data.get("first_name")
        last_name = self.cleaned_data.get("last_name")
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")
        user = models.User.objects.create_user(email, email=email, password=password)
        user.first_name = first_name
        user.last_name = last_name
        user.save()

users/views.py
import os
import requests
from django.utils import translation
from django.http import HttpResponse
from django.views.generic import FormView, DetailView, UpdateView
from django.contrib.auth.views import PasswordChangeView
from django.shortcuts import redirect, reverse
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.core.files.base import ContentFile
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from . import models, forms, mixins


class LoginView(mixins.LoggedOutOnlyView, FormView):

    template_name = "users/login.html"
    form_class = forms.LoginForm

    def form_valid(self, form):
        email = form.cleaned_data.get("email")
        password = form.cleaned_data.get("password")
        user = authenticate(self.request, username=email, password=password)
        if user is not None:
            login(self.request, user)
        return super().form_valid(form)

    def get_success_url(self):
        next_arg = self.request.GET.get("next")
        if next_arg is not None:
            return next_arg
        else:
            return reverse("core:home")


"""
class LoginView(View):
    def get(self, request):
        form = forms.LoginForm(initial={"email": "alsrn7590@naver.com"})
        return render(request, "users/login.html", {"form": form})

    def post(self, request):
        form = forms.LoginForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data.get("email")
            password = form.cleaned_data.get("password")
            user = authenticate(request, username=email, password=password)
            if user is not None:
                login(request, user)
                return redirect(reverse("core:home"))
        return render(request, "users/login.html", {"form": form})
"""


def log_out(request):
    logout(request)
    messages.info(request, "See you later")
    return redirect(reverse("core:home"))


class SignUpView(mixins.LoggedOutOnlyView, FormView):
    template_name = "users/signup.html"
    form_class = forms.SignUpForm
    success_url = reverse_lazy("core:home")
    initial = {
        "first_name": "Mingu",
        "last_name": "Kang",
        "email": "alsrn7590@gmail.com",
    }

    def form_valid(self, form):
        form.save()
        email = form.cleaned_data.get("email")
        password = form.cleaned_data.get("password")
        user = authenticate(self.request, username=email, password=password)
        if user is not None:
            login(self.request, user)
        user.verify_email()
        return super().form_valid(form)


def complete_verification(request, key):
    try:
        user = models.User.objects.get(email_secret=key)
        user.email_verified = True
        user.email_secret = ""
        user.save()
        # to do : add success message
    except models.User.DoesNotExist:
        # to do : add error message
        pass
    return redirect(reverse("core:home"))


def github_login(request):
    client_id = os.environ.get("GH_ID")
    redirect_uri = "http://127.0.0.1:8000/users/login/github/callback"
    return redirect(
        f"https://github.com/login/oauth/authorize?client_id={client_id}&redirect_uri={redirect_uri}&scope=read:user"
    )


class GithubException(Exception):
    pass


def github_callback(request):
    try:
        client_id = os.environ.get("GH_ID")
        client_secret = os.environ.get("GH_SECRET")
        code = request.GET.get("code", None)
        if code is not None:
            token_request = requests.post(
                f"https://github.com/login/oauth/access_token?client_id={client_id}&client_secret={client_secret}&code={code}",
                headers={"Accept": "application/json"},
            )
            token_json = token_request.json()
            error = token_json.get("error", None)
            if error is not None:
                raise GithubException("Can't get access token")
            else:
                access_token = token_json.get("access_token")
                api_request = requests.get(
                    "https://api.github.com/user",
                    headers={
                        "Authorization": f"token {access_token}",
                        "Accept": "application/json",
                    },
                )
                profile_json = api_request.json()
                username = profile_json.get("login", None)
                if username is not None:
                    name = profile_json.get("name")
                    email = profile_json.get("email")
                    bio = profile_json.get("bio")
                    try:
                        user = models.User.objects.get(email=email)
                        if user.login_method != models.User.LOGIN_GITHUB:
                            raise GithubException(
                                f"Please log in with:{user.login_method}"
                            )
                    except models.User.DoesNotExist:
                        user = models.User.objects.create(
                            email=email,
                            first_name=name,
                            username=email,
                            bio=bio,
                            login_method=models.User.LOGIN_GITHUB,
                            email_verified=True,
                        )
                        user.set_unusable_password()
                        user.save()
                    login(request, user)
                    messages.success(request, f"Welcome back {user.first_name}")
                    return redirect(reverse("core:home"))
                else:
                    raise GithubException("Can't get your profile")
        else:
            raise GithubException("Can't get code")
    except GithubException as e:
        messages.error(request, e)
        return redirect(reverse("users:login"))


def kakao_login(request):
    client_id = os.environ.get("KAKAO_ID")
    redirect_uri = "http://127.0.0.1:8000/users/login/kakao/callback"
    return redirect(
        f"https://kauth.kakao.com/oauth/authorize?client_id={client_id}&redirect_uri={redirect_uri}&response_type=code"
    )


class KakaoException(Exception):
    pass


def kakao_callback(request):
    try:
        code = request.GET.get("code")
        client_id = os.environ.get("KAKAO_ID")
        redirect_uri = "http://127.0.0.1:8000/users/login/kakao/callback"
        token_request = requests.get(
            f"https://kauth.kakao.com/oauth/token?grant_type=authorization_code&client_id={client_id}&redirect_uri={redirect_uri}&code={code}"
        )
        token_json = token_request.json()
        error = token_json.get("error", None)
        if error is not None:
            raise KakaoException("Can't get authorization code.")
        access_token = token_json.get("access_token")
        profile_request = requests.get(
            "https://kapi.kakao.com/v2/user/me",
            headers={"Authorization": f"Bearer {access_token}"},
        )
        profile_json = profile_request.json()
        kakao_account = profile_json.get("kakao_account")
        email = kakao_account.get("email", None)
        if email is None:
            raise KakaoException("Please also give me your email")
        profile = kakao_account.get("profile", None)
        nickname = profile.get("nickname", None)
        profile_image = profile.get("profile_image_url", None)
        try:
            user = models.User.objects.get(email=email)
            if user.login_method != models.User.LOGIN_KAKAO:
                raise KakaoException(f"Please log in with: {user.login_method}")
        except models.User.DoesNotExist:
            user = models.User.objects.create(
                email=email,
                username=email,
                first_name=nickname,
                login_method=models.User.LOGIN_KAKAO,
                email_verified=True,
            )
            user.set_unusable_password()
            user.save()
            if profile_image is not None:
                photo_request = requests.get(profile_image)
                user.avatar.save(
                    f"{nickname}-avatar", ContentFile(photo_request.content)
                )
        login(request, user)
        messages.success(request, f"Welcome back {user.first_name}")
        return redirect(reverse("core:home"))
    except KakaoException as e:
        messages.error(request, e)
        return redirect(reverse("users:login"))


class UserPofileView(DetailView):
    model = models.User
    context_object_name = "user_obj"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class UpdateProfileView(mixins.LoggedInOnlyView, SuccessMessageMixin, UpdateView):

    model = models.User
    template_name = "users/update-profile.html"
    fields = (
        "first_name",
        "last_name",
        "gender",
        "bio",
        "birthdate",
        "language",
        "currency",
    )
    success_message = "Profile Updated"

    def get_object(self, queryset=None):
        return self.request.user

    def get_form(self, form_class=None):
        form = super().get_form(form_class=form_class)
        form.fields["first_name"].widget.attrs = {"placeholder": "First name"}
        form.fields["last_name"].widget.attrs = {"placeholder": "Last name"}
        form.fields["bio"].widget.attrs = {"placeholder": "Bio"}
        form.fields["birthdate"].widget.attrs = {"placeholder": "Birthdate"}
        return form


class UpdatePasswordView(
    mixins.LoggedInOnlyView,
    mixins.EmailLoginOnlyView,
    SuccessMessageMixin,
    PasswordChangeView,
):

    template_name = "users/update-password.html"
    success_message = "Passwords Updated"

    def get_form(self, form_class=None):
        form = super().get_form(form_class=form_class)

templates/users/login.html
{% extends 'base.html' %}


{% block page_title %}
    Log In
{% endblock page_title %}


{% block search-bar %}
{% endblock search-bar %}


{% block content %}

    <div class="container lg:w-5/12 md:w-1/2 xl:w-1/3 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">
        {% include 'partials/social_login.html' %}
        
        {% include 'mixins/auth/auth_form.html' with form=form cta="Log in" %}

        <div class="mt-5">
            <span class="mr-2">Don't have an account?</span>
            <a href="{% url 'users:signup' %}" class="text-green-500 font-medium">Sign up</a>
        </div>
    </div>
{% endblock content %}
    

templates/users/signup.html
{% extends 'base.html' %}


{% block page_title %}
    Sign up
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}
    <div class="container lg:w-5/12 md:w-1/2 xl:w-1/3 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">
        {% include 'partials/social_login.html' %}
    
        {% include 'mixins/auth/auth_form.html' with form=form cta="Sign up" %}

        <div class="mt-5">
            <span class="mr-2">Have an account?</span>
            <a href="{% url 'users:login' %}" class="text-green-500 font-medium">Log in</a>
        </div>
    </div>
{% endblock content %}
    

templates/users/update-password.html
{% extends 'base.html' %}


{% block page_title %}
    Update Password
{% endblock page_title %}


{% block content %}
<div class="min-h-75vh">
    <div class="container lg:w-5/12 md:w-1/2 xl:w-1/3 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">
        {% include 'mixins/auth/auth_form.html' with form=form cta="Update Password" %}
    </div>
</div>
{% endblock content %}
    

templates/users/update-profile.html
{% extends 'base.html' %}


{% block page_title %}
    Update Profile
{% endblock page_title %}


{% block content %}
    <div class="container lg:w-5/12 md:w-1/2 xl:w-1/3 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">
        {% include 'mixins/auth/auth_form.html' with form=form cta="Update Profile" %}
        
        {{object.login_method}}
        
        {% if object.login_method == "email" %}
            <div class="mt-5">
                <a href="{% url 'users:password' %}" class="text-green-500 font-medium">Change Password</a>
            </div>        
        {% endif %}
            

    </div>
{% endblock content %}
    

templates/users/user_detail.html
{% extends 'base.html' %}

{% block page_title %}
    {{user_obj.first_name}}'s Profile
{% endblock page_title %}


{% block content %}
    <div class="min-h-75vh">
        <div class="container lg:w-5/12 md:w-1/2 xl:w-1/3 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">
 
            {% include "mixins/user_avatar.html" with user=user_obj %}
            
            <div class="flex items-center">
                <span class="text-3xl mt-2">{{user_obj.first_name}}</span>
                {% if user_obj.superhost %}
                    <i class="fas fa-check-circle text-green-400 ml-1"></i>
                {% endif %}    
            </div>         
    
            <span class="text-lg mb-5">{{user_obj.bio}}</span>
    
            {% if user == user_obj %}
            <a href="{% url 'users:update' %}" class="btn-link">Edit Profile</a>
            <div class="flex justify-between w-40 mt-5">
                <a href="{% url 'lists:see-favs' %}" class="flex flex-col items-center">
                    <i class="fas fa-heart text-pink-500">({{user.list.rooms.count}})</i>
                    <span>Favs</span>
                </a>
                <a href="{% url 'conversations:see-mine' %}" class="flex flex-col items-center">
                    <i class="far fa-comment-dots">({{user.conversations.count}})</i>
                    <span>Messages</span>
                </a>
            </div>
            {% endif %}
        </div>
                
        {% if user_obj.rooms.count > 0 %}
            <div class="container mx-auto pb-10 flex flex-col items-center">
                <h3 class="mb-12 text-2xl">{{user_obj.first_name}}'s Room</h3>
                <div class="flex flex-wrap -mx-40 mb-10 w-full"> 
                    {% for room in user_obj.rooms.all %}
                        {% include 'mixins/room_card.html' with room=room %}
                    {% endfor %}            
                </div>
            </div>        
        {% endif %}
    </div>

{% endblock content %}
    